In [1]:
# Importing libraries
import pandas as pd
import numpy as np

In [3]:
#Importing dataset
df = pd.read_csv(r'C:\Users\Sirmoi Wekesa\Downloads\messy_synthetic_data.csv')
df.head()

,Employee ID,Name,Age,Salary,City,Department,Join Date,Email
0,0.0,Jack,30,"60,000",Nairobi,NaN,not_a_date,NaN
1,NaN,Al!ce,27,50000,nakuru,Sales,not_a_date,NaN
2,2.0,NaN,200,"60,000",kisumu,sales,2024/13/01,test@example.com
3,3.0,Alice,25,KES 80000,kisumu,NaN,2024-01-05,NaN
4,4.0,Al!ce,200,KES 80000,kisumu,Finance,05/01/2024,USER@MAIL.COM

In [5]:
#Understanding structure
df.shape
df.columns

Index([' Employee ID ', 'Name ', 'Age', 'Salary ', 'City', 'Department',
       'Join Date', 'Email'],
      dtype='object')

In [6]:
# Cleaning column names
df.columns = df.columns.str.strip().str.lower().str.replace(' ','_')

In [7]:
#Checking out column names again
df.columns

Index(['employee_id', 'name', 'age', 'salary', 'city', 'department',
       'join_date', 'email'],
      dtype='object')

In [8]:
# Checking missing values
df.isnull().sum()

employee_id    36
name           18
age            15
salary         37
city           25
department     29
join_date      26
email          58
dtype: int64

In [14]:
#Checking data types
df.dtypes

employee_id    float64
name            object
age            float64
salary         float64
city            object
department      object
join_date       object
email           object
dtype: object

In [15]:
#Changing to date time format
df['join_date'] = pd.to_datetime(df['join_date'], errors='coerce')

C:\Users\Sirmoi Wekesa\AppData\Local\Temp\ipykernel_9836\2220971616.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['join_date'] = pd.to_datetime(df['join_date'], errors='coerce')

In [16]:
df.dtypes

employee_id           float64
name                   object
age                   float64
salary                float64
city                   object
department             object
join_date      datetime64[ns]
email                  object
dtype: object

In [19]:
#changing name column to string
df['name'] = df['name']. astype(str)

In [22]:
df.dtypes

employee_id           float64
name                   object
age                   float64
salary                float64
city                   object
department             object
join_date      datetime64[ns]
email                  object
dtype: object

In [23]:
#Handling missing values
df.isnull().sum()

employee_id    36
name            0
age            41
salary         77
city           25
department     29
join_date      74
email          58
dtype: int64

In [24]:
#replacing null values within the slary column with the mean
df['salary'] = df['salary'].fillna(df['salary'].mean())

In [26]:
df.isnull().sum()

employee_id    36
name            0
age            41
salary          0
city           25
department     29
join_date      74
email          58
dtype: int64

In [69]:
df['age'] = df['age'].fillna(df['age'].median())

C:\Users\Sirmoi Wekesa\AppData\Local\Temp\ipykernel_9836\3541415502.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['age'] = df['age'].fillna(df['age'].median())

In [68]:
df.isnull().sum()

employee_id    19
name            0
age             0
salary          0
city            0
department      0
join_date      43
email           0
dtype: int64

In [31]:
df['department'] = df['department'].fillna('unknown')
df['city'] = df['city'].fillna(df['city'].mode()[0])
df['join_date'] = df['join_date'].fillna('unknown')
df['email'] = df['email'].fillna('unknown')

In [32]:
df.isnull().sum()

employee_id    36
name            0
age             0
salary          0
city            0
department      0
join_date       0
email           0
dtype: int64

In [34]:
# Checking duplicates
df.duplicated().sum()

np.int64(3)

In [36]:
#View duplicated
df[df.duplicated()]

,employee_id,name,age,salary,city,department,join_date,email
120,NaN,Eve,25.0,63587.228261,Nairobi,HR,unknown,test@example.com
121,NaN,Alice,27.0,63587.228261,eldoret,HR,2024-05-01 00:00:00,unknown
122,15.0,Al!ce,27.0,63587.228261,MOMBASA,HR,2024-01-05 00:00:00,unknown

In [38]:
#DROPPING DUPLICATES
df.drop_duplicates(inplace = True)
df.duplicated().sum()

np.int64(0)

In [39]:
# checking data types
df.dtypes

employee_id    float64
name            object
age            float64
salary         float64
city            object
department      object
join_date       object
email           object
dtype: object

In [44]:
df['age'] = df['age'].astype(int)
df['join_date'] = pd.to_datetime(
    df['join_date'],
    errors='coerce',
    format='mixed'
)

In [45]:
df.dtypes

employee_id           float64
name                   object
age                     int64
salary                float64
city                   object
department             object
join_date      datetime64[ns]
email                  object
dtype: object

In [46]:
#Standardizing text
df['name'].unique()

array(['Jack', 'Al!ce', 'nan', ' Alice ', 'Eve', 'Ivy', 'Henry', 'Grace',
       'Frank', 'CHARLIE', 'bob', 'Diana'], dtype=object)

In [47]:
df['name'] = df['name'].replace({
    'Al!ce': 'Alice',
    'nan': 'NaN',
    'CHARLIE': 'Charlie',
    'bob': 'Bob'
})

In [50]:
df['city'] = df['city'].str.title()

In [51]:
df['city'].unique()

array([' Nairobi ', 'Nakuru', 'Kisumu', 'Nairobi', 'Eldoret', 'Mombasa'],
      dtype=object)

In [52]:
df['department'].unique()

array(['unknown', 'Sales', 'sales', 'Finance', 'HR', 'IT', 'hr'],
      dtype=object)

In [53]:
df['department'] = df['department'].str.title()

In [54]:
df['department'].unique()

array(['Unknown', 'Sales', 'Finance', 'Hr', 'It'], dtype=object)

In [55]:
df['email'] = df['email'].str.lower()

In [56]:
df['email'].unique()

array(['unknown', 'test@example.com', 'user@mail.com', 'bademail'],
      dtype=object)

In [59]:
# Handling outliers
# Handling outliers
Q1 = df['salary'].quantile(0.25)
Q3 = df['salary'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

df = df[(df['salary'] >= lower) & (df['salary'] <= upper)]

In [60]:
# Fixing wrong entries
df[df['age'] < 0]

#Replace
df.loc[df['age'] < 0, 'age'] = np.nan

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 74 entries, 0 to 119
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   employee_id  55 non-null     float64
 1   name         74 non-null     object
 2   age          64 non-null     float64
 3   salary       74 non-null     float64
 4   city         74 non-null     object
 5   department   74 non-null     object
 6   join_date    31 non-null     datetime64[ns]
 7   email        74 non-null     object
dtypes: datetime64[ns](1), float64(3), object(4)
memory usage: 5.2+ KB

In [62]:
df.describe()

       employee_id         age        salary                      join_date
count    55.000000   64.000000  7.400000e+01                             31
mean     63.472727   42.937500  6.358723e+04  2024-03-01 14:42:34.838709760
min       0.000000   25.000000  6.358723e+04            2024-01-05 00:00:00
25%      30.500000   27.000000  6.358723e+04            2024-01-05 00:00:00
50%      70.000000   27.000000  6.358723e+04            2024-01-05 00:00:00
75%      94.000000   30.000000  6.358723e+04            2024-05-01 00:00:00
max     119.000000  200.000000  6.358723e+04            2024-05-01 00:00:00
std      36.944831   46.478148  7.325623e-12                            NaN

In [63]:
df.isnull().sum()

employee_id    19
name            0
age            10
salary          0
city            0
department      0
join_date      43
email           0
dtype: int64

In [65]:
df.to_csv('cleaned_file.csv', index = False)

In [66]:
import os
os.getcwd()

'C:\\Users\\Sirmoi Wekesa\\Downloads'

In [ ]:
importing